- control_profile:                      Vanilla MPPI with obstacle costs
  apply_safety_filter_to_final_control: false
  apply_safety_filter_to_samples:       false
  cost_from_obstacles_or_BRT:           obs

- control_profile:                      Vanilla MPPI with BRT costs
  apply_safety_filter_to_final_control: false
  apply_safety_filter_to_samples:       false
  cost_from_obstacles_or_BRT:           brt

- control_profile:                      Filtered MPPI with obstacle costs
  apply_safety_filter_to_final_control: true
  apply_safety_filter_to_samples:       false
  cost_from_obstacles_or_BRT:           obs

- control_profile:                      Filtered MPPI with BRT costs
  apply_safety_filter_to_final_control: true
  apply_safety_filter_to_samples:       false
  cost_from_obstacles_or_BRT:           brt

- control_profile:                      Sample-safe MPPI (our method)
  apply_safety_filter_to_final_control: true   # Hopefully, shouldn't matter
  apply_safety_filter_to_samples:       true
  cost_from_obstacles_or_BRT:           obs    # Should be irrelevant, as samples will never enter BRT or obstacles
