# control profile params (for ablation)
control_profile: Vanilla MPPI with obstacle costs
apply_safety_filter_to_final_chosen_control: false
apply_safety_filter_to_nominal_trajectory: false
apply_safety_filter_to_samples: false
cost_from_obstacles_or_BRT: obs     # one of: obs, brt

# output params
save_samples: false

# trial params
init_state: [3.375, 3.482, 2.604]   # [x, y, theta] (m, m, rad)
goal_state: [1.0, 1.0, 0.0]         # [x, y, theta] (m, m, rad)

timestep: 0.02           # dynamics update time interval (s)
trial_max_duration: 15   # after this much time, trial terminates (s)

# mppi params
mppi_samples: 500        # Number of samples to forward-simulate
mppi_horizon: 25         # How many dynamics steps to propagate per sample
mppi_temperature: 5.0    # Higher means update incorporates votes of more samples 
mppi_angvel_control_noise_mean:    0.0   # mean of control noise (rad/s)
mppi_angvel_control_noise_stddev:  8.0   # stddev of control noise (rad/s)
mppi_initial_control_is_mean:      false # if True, initial control is noise_mean; else random

# brt & safety filter params
brt_filename: config/brt_dubins_cluttered_0.hdf5
safety_filter_type: least_restrictive
safety_filter_value_threshold: 0.01

# dynamics params
dynamics_name: dubins
state_dim: 3
state_labels: ['x', 'y', 'theta']
control_dim: 1
control_labels: ['angvel']
dynamics_linvel: 4.0         # fixed linear velocity (m/s)
dynamics_angvel_min: -6.0    # minimum angular velocity (rad/s)
dynamics_angvel_max:  6.0    # maximum angular velocity (rad/s)

# cost params
Phi_terminal_state_cost_weights: [0.0, 0.0, 0.0]  # Currently unused
Q_running_state_cost_weights: [1.0, 1.0, 0.0]
action_cost_weights: 0.2
