# ablation params
apply_safety_filter_to_samples: true
apply_safety_filter_to_nominal_trajectory: false
cost_from_obstacles_or_BRT: obs     # one of: obs, brt

# output params
save_samples: false

# trial params
trial_max_duration: 0.2             # (s)   ...prev: 15
init_state: [3.375, 3.482, 2.604]   # [x, y, theta] (m, m, rad)
goal_state: [1.0, 1.0, 0.0]         # [x, y, theta] (m, m, rad)

timestep: 0.02      # dynamics update time interval (s)

# mppi params
mppi_samples: 500        # Number of samples to forward-simulate
mppi_horizon: 25         # How many dynamics steps to propagate per sample
mppi_temperature: 5.0    # Higher means ____?
mppi_angvel_control_noise_mean:    0.0   # mean of control noise (rad/s)
mppi_angvel_control_noise_stddev:  8.0   # stddev of control noise (rad/s)
mppi_initial_control_is_mean:      False # if True, initial control is noise_mean; else random

# brt & safety filter params
brt_filename: brt_dubins_cluttered_1.hdf5
safety_filter_type: least_restrictive
safety_filter_value_threshold: 0.01

# dynamics params
dynamics_name: dubins
state_dim: 3
state_labels: ['x', 'y', 'theta']
control_dim: 1
control_labels: ['angvel']
dynamics_linvel: 4.0         # fixed linear velocity (m/s)
dynamics_angvel_min: -6.0    # minimum angular velocity (rad/s)
dynamics_angvel_max:  6.0    # maximum angular velocity (rad/s)

# cost params
Phi_terminal_state_cost_weights: [0.0, 0.0, 0.0]  # Currently unused
Q_running_state_cost_weights: [1.0, 1.0, 0.0]
action_cost_weights: 0.2
